#!/bin/bash

if [ "${PACKAGE_NAME}" = "amber-ce-bookworm" ];then
if [ -e /opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bookworm-env ];then
if [ "$(arch)" != "loongarch64" ];then
mv /opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bookworm-env /opt/apps/amber-ce-bookworm/files/ace-env
rm -rf /opt/apps/cn.flamescion.bookworm-compatibility-mode
fi
fi
fi
