#!/bin/bash

PACKAGE_NAME="$DPKG_MAINTSCRIPT_PACKAGE"

if [ "${PACKAGE_NAME}" = "cn.flamescion.bookworm-compatibility-mode" ];then
if [ -e /opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bookworm-env ];then
if [ "$(arch)" != "loongarch64" ];then
mv /opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bookworm-env /opt/apps/cn.flamescion.bookworm-compatibility-mode/files/ace-env
ln -sfv /opt/apps/cn.flamescion.bookworm-compatibility-mode/files/ace-env /opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bookworm-env
else
mv /opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bookworm-env /opt/apps/amber-ce-loongnix/files/ace-env 
fi
fi
fi
