version: '1.0'
name: Debian-Build-amd64
displayName: Debian-Build-amd64
triggers:
  trigger: manual
  push:
    tags:
      prefix:
        - ''
stages:
  - name: stage-d1472d18
    displayName: Build DEB
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: Build Debian amd64
        certificate: ''
        image: docker.jianmuhub.com/library/debian:bookworm
        command:
          - export DEBIAN_FRONTEND=noninteractive
          - echo 'deb [trusted=yes] http://mirrors.sdu.edu.cn/debian bookworm main contrib non-free non-free-firmware' > /etc/apt/sources.list
          - rm -rfv /etc/apt/sources.list.d/*
          - apt update
          - apt build-dep . -y
          - dpkg-buildpackage -b -us -uc
          - cd ..
          - ls -all
          - mkdir target
          - for f in $(find . -type f -name "*.deb")
          - 'do '
          - mv $f target
          - done
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        notify: []
        strategy:
          retry: '0'
  - name: stage-41e41b9f
    displayName: push
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        notify: []
        strategy:
          retry: '0'
